# Generated by Django 4.2.5 on 2023-09-20 15:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("user_profiles", "0003_profile_otp"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="last_mail",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
