# Generated by Django 4.2.5 on 2023-09-20 02:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bbs", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
